// <auto-generated />
using System;
using Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20241128222157_InitialMigration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "uuid-ossp");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Domain.Entities.Constraint", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<string>("CourseName")
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Day")
                        .HasColumnType("text");

                    b.Property<string>("Event")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("GroupName")
                        .HasColumnType("character varying(200)");

                    b.Property<Guid?>("ProfessorId")
                        .HasColumnType("uuid");

                    b.Property<string>("RoomName")
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Time")
                        .HasColumnType("text");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<string>("WantedDay")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("WantedRoomName")
                        .HasColumnType("character varying(200)");

                    b.Property<string>("WantedTime")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("CourseName");

                    b.HasIndex("GroupName");

                    b.HasIndex("ProfessorId");

                    b.HasIndex("RoomName");

                    b.HasIndex("WantedRoomName");

                    b.ToTable("constraints", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Course", b =>
                {
                    b.Property<string>("CourseName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("Credits")
                        .HasColumnType("integer");

                    b.Property<string>("Level")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Package")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("Semester")
                        .HasColumnType("integer");

                    b.HasKey("CourseName");

                    b.ToTable("courses", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Group", b =>
                {
                    b.Property<string>("Name")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Name");

                    b.ToTable("groups", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Professor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.ToTable("professors", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Room", b =>
                {
                    b.Property<string>("Name")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("Capacity")
                        .HasColumnType("integer");

                    b.HasKey("Name");

                    b.ToTable("rooms", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Timetable", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("timetables", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Constraint", b =>
                {
                    b.HasOne("Domain.Entities.Course", null)
                        .WithMany()
                        .HasForeignKey("CourseName")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Domain.Entities.Group", null)
                        .WithMany()
                        .HasForeignKey("GroupName")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Domain.Entities.Professor", null)
                        .WithMany()
                        .HasForeignKey("ProfessorId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Domain.Entities.Room", null)
                        .WithMany()
                        .HasForeignKey("RoomName")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Domain.Entities.Room", null)
                        .WithMany()
                        .HasForeignKey("WantedRoomName");
                });

            modelBuilder.Entity("Domain.Entities.Timetable", b =>
                {
                    b.OwnsMany("Domain.Entities.Timeslot", "Timeslots", b1 =>
                        {
                            b1.Property<string>("Time")
                                .HasColumnType("text");

                            b1.Property<string>("Day")
                                .HasColumnType("text");

                            b1.Property<string>("RoomName")
                                .HasColumnType("text");

                            b1.Property<bool>("IsAvailable")
                                .HasColumnType("boolean");

                            b1.Property<Guid>("TimetableId")
                                .HasColumnType("uuid");

                            b1.HasKey("Time", "Day", "RoomName");

                            b1.HasIndex("TimetableId");

                            b1.ToTable("timeslots", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("TimetableId");

                            b1.OwnsOne("Domain.Entities.Event", "Event", b2 =>
                                {
                                    b2.Property<string>("TimeslotTime")
                                        .HasColumnType("text");

                                    b2.Property<string>("TimeslotDay")
                                        .HasColumnType("text");

                                    b2.Property<string>("TimeslotRoomName")
                                        .HasColumnType("text");

                                    b2.Property<string>("CourseName")
                                        .IsRequired()
                                        .HasColumnType("text")
                                        .HasColumnName("CourseName");

                                    b2.Property<string>("EventName")
                                        .IsRequired()
                                        .HasColumnType("text")
                                        .HasColumnName("EventName");

                                    b2.Property<string>("Group")
                                        .IsRequired()
                                        .HasColumnType("text")
                                        .HasColumnName("Group");

                                    b2.Property<Guid>("ProfessorId")
                                        .HasColumnType("uuid")
                                        .HasColumnName("ProfessorId");

                                    b2.Property<bool>("WeekEvenness")
                                        .HasColumnType("boolean")
                                        .HasColumnName("WeekEvenness");

                                    b2.HasKey("TimeslotTime", "TimeslotDay", "TimeslotRoomName");

                                    b2.ToTable("timeslots");

                                    b2.WithOwner()
                                        .HasForeignKey("TimeslotTime", "TimeslotDay", "TimeslotRoomName");
                                });

                            b1.Navigation("Event")
                                .IsRequired();
                        });

                    b.Navigation("Timeslots");
                });
#pragma warning restore 612, 618
        }
    }
}
