// <auto-generated />
using System;
using Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20241207113229_Updated")]
    partial class Updated
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "uuid-ossp");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Domain.Entities.Constraint", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<Guid?>("CourseId")
                        .HasColumnType("uuid");

                    b.Property<string>("Day")
                        .HasColumnType("text");

                    b.Property<string>("Event")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid?>("GroupId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ProfessorId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("RoomId")
                        .HasColumnType("uuid");

                    b.Property<string>("Time")
                        .HasColumnType("text");

                    b.Property<Guid>("TimetableId")
                        .HasColumnType("uuid");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<string>("WantedDay")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid?>("WantedRoomId")
                        .HasColumnType("uuid");

                    b.Property<string>("WantedTime")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("CourseId");

                    b.HasIndex("GroupId");

                    b.HasIndex("ProfessorId");

                    b.HasIndex("RoomId");

                    b.HasIndex("WantedRoomId");

                    b.ToTable("constraints", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Course", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<string>("CourseName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("Credits")
                        .HasColumnType("integer");

                    b.Property<string>("Level")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Package")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("Semester")
                        .HasColumnType("integer");

                    b.Property<string>("UserEmail")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("courses", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Group", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("UserEmail")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("groups", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Professor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("UserEmail")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("professors", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Room", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<int>("Capacity")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("UserEmail")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("rooms", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Timetable", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("UserEmail")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("timetables", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.User", b =>
                {
                    b.Property<string>("Email")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("AccountType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Email");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Constraint", b =>
                {
                    b.HasOne("Domain.Entities.Course", null)
                        .WithMany()
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Domain.Entities.Group", null)
                        .WithMany()
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Domain.Entities.Professor", null)
                        .WithMany()
                        .HasForeignKey("ProfessorId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Domain.Entities.Room", null)
                        .WithMany()
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Domain.Entities.Room", null)
                        .WithMany()
                        .HasForeignKey("WantedRoomId");
                });

            modelBuilder.Entity("Domain.Entities.Course", b =>
                {
                    b.HasOne("Domain.Entities.User", null)
                        .WithMany("Courses")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Domain.Entities.Group", b =>
                {
                    b.HasOne("Domain.Entities.User", null)
                        .WithMany("Groups")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Domain.Entities.Professor", b =>
                {
                    b.HasOne("Domain.Entities.User", null)
                        .WithMany("Professors")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Domain.Entities.Room", b =>
                {
                    b.HasOne("Domain.Entities.User", null)
                        .WithMany("Rooms")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Domain.Entities.Timetable", b =>
                {
                    b.HasOne("Domain.Entities.User", null)
                        .WithMany("Timetables")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.OwnsMany("Domain.Entities.Timeslot", "Timeslots", b1 =>
                        {
                            b1.Property<Guid>("TimetableId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Time")
                                .HasColumnType("text");

                            b1.Property<string>("Day")
                                .HasColumnType("text");

                            b1.Property<string>("RoomName")
                                .HasColumnType("text");

                            b1.Property<bool>("IsAvailable")
                                .HasColumnType("boolean");

                            b1.Property<Guid>("RoomId")
                                .HasColumnType("uuid");

                            b1.HasKey("TimetableId", "Time", "Day", "RoomName");

                            b1.ToTable("timeslots", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("TimetableId");

                            b1.OwnsOne("Domain.Entities.Event", "Event", b2 =>
                                {
                                    b2.Property<Guid>("TimeslotTimetableId")
                                        .HasColumnType("uuid");

                                    b2.Property<string>("TimeslotTime")
                                        .HasColumnType("text");

                                    b2.Property<string>("TimeslotDay")
                                        .HasColumnType("text");

                                    b2.Property<string>("TimeslotRoomName")
                                        .HasColumnType("text");

                                    b2.Property<int>("CourseCredits")
                                        .HasColumnType("integer")
                                        .HasColumnName("CourseCredits");

                                    b2.Property<Guid>("CourseId")
                                        .HasColumnType("uuid")
                                        .HasColumnName("CourseId");

                                    b2.Property<string>("CourseName")
                                        .IsRequired()
                                        .HasColumnType("text")
                                        .HasColumnName("CourseName");

                                    b2.Property<string>("CoursePackage")
                                        .IsRequired()
                                        .HasColumnType("text")
                                        .HasColumnName("CoursePackage");

                                    b2.Property<string>("EventName")
                                        .IsRequired()
                                        .HasColumnType("text")
                                        .HasColumnName("EventName");

                                    b2.Property<string>("Group")
                                        .IsRequired()
                                        .HasColumnType("text")
                                        .HasColumnName("Group");

                                    b2.Property<Guid>("GroupId")
                                        .HasColumnType("uuid")
                                        .HasColumnName("GroupId");

                                    b2.Property<Guid>("ProfessorId")
                                        .HasColumnType("uuid")
                                        .HasColumnName("ProfessorId");

                                    b2.Property<string>("ProfessorName")
                                        .IsRequired()
                                        .HasColumnType("text")
                                        .HasColumnName("ProfessorName");

                                    b2.Property<int>("TimeInterval")
                                        .HasColumnType("integer");

                                    b2.Property<bool>("WeekEvenness")
                                        .HasColumnType("boolean")
                                        .HasColumnName("WeekEvenness");

                                    b2.HasKey("TimeslotTimetableId", "TimeslotTime", "TimeslotDay", "TimeslotRoomName");

                                    b2.ToTable("timeslots");

                                    b2.WithOwner()
                                        .HasForeignKey("TimeslotTimetableId", "TimeslotTime", "TimeslotDay", "TimeslotRoomName");
                                });

                            b1.Navigation("Event")
                                .IsRequired();
                        });

                    b.Navigation("Timeslots");
                });

            modelBuilder.Entity("Domain.Entities.User", b =>
                {
                    b.Navigation("Courses");

                    b.Navigation("Groups");

                    b.Navigation("Professors");

                    b.Navigation("Rooms");

                    b.Navigation("Timetables");
                });
#pragma warning restore 612, 618
        }
    }
}
